from . import help
from . import ruyxatHandlers
from . import send_photos
from . import dostafkaHandlers
from . import admin
from . import aloqa
from . import help
from . import start
from . import donar
from . import myaso
from . import menu
from . import menyular
from . import savatHENDLER
from . import inlineKeyboard
from . import burger
from . import pitsa
from . import hotdog
from . import pitta
from . import nondog
from . import ichimlik
from . import cocacolalar
from . import languageHandlers
from . import fri
from . import shirinlik
from . import doc_handlers
from . import location_handler
from . import contact_handler
from . import lavashKeyboard
from . import start
from . import echo
from . import echo
