from . import productsKeyboard
from . import burgerKeyboard
from . import pitsaKeyboard
from . import hotDogKeyboard
from . import pittaKeyboard
from . import nonDog
from . import ichimliklar
from . import shirinlikKeyboard
from . import cocolaMenu
from . import pepsiKeyboard
from . import fantaKeyboard
from . import sokKeyboard
from . import flashKeyboard
from . import nistleKeyboard
from . import spriteKeyboard
from . import familyKeyboard
from . import KofeKeyboard
from . import buy_book
from . import TilKeyboards
from . import klaviaturaKeyboard
from . import callback_data
from . import menu_keyboards
